export const PLAYERS = ["Tim", "Sasha", "Tommy", "Sarah", "Bobby", "Dan", "Bennya", "Sidd", "Luke", "Estela", "Jessy"]

export const DECKS = [
    "Aang, at the Crossroads",
    "Alela, Artful Provocateur",
    "Arabella, Abandoned Doll",
    "Auntie Ool, Cursewretch",
    "Bello, Bard of the Brambles",
    "Beorn, the Fierce",
    "Caesar, Legion’s Emperor",
    "Captain America, Team Leader",
    "Edward Kenway",
    "Ghalta, Stampede Tyrant",
    "Hakbal of the Surging Soul",
    "Heliod, Sun Crowned",
    "Huatli, Poet of Unity",
    "Indominus Rex, Alpha",
    "Inspirit, Flagship Vessel",
    "Ishhin, Two Heavens as One",
    "Jon Irenicus, Shattered One",
    "Kardur, Doomscourge",
    "Kardur, Timscourge",
    "Kilo, Apogee Mind",
    "Kratos, God of War",
    "Krenko, Mob Boss",
    "Magda, Brazen Outlaw",
    "Marisi, Breaker of the Coil",
    "Nelly Borca, Impulsive Accuser",
    "Nashi, Searcher in the Dark",
    "Ozai, the Phoenix King",
    "Phabine, Boss's Confidant",
    "Polukranos, Reborn",
    "Red Death, Shipwrecker",
    "Sauron, Lord of the Rings",
    "Selvala, Explorer Returned",
    "Shilgengar, Sire of Famine",
    "Terra, Herald of Hope",
    "Teval, the Balanced Scale",
    "The Scarab God",
    "The Lord of Pain",
    "Tidus, Yuna's Guardian",
    "Volo, Guide to Monsters",
    "Wayta, Trainer Prodigy",
    "Xantcha, Sleeper Agent",
]
